apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.nameWithEnv" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/instance: {{ include "app.nameWithEnv" . }}
    app.kubernetes.io/component: application
    backstage.io/kubernetes-id: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
      app.kubernetes.io/instance: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        app.kubernetes.io/instance: {{ .Values.app.name }}
        app.kubernetes.io/component: application
        backstage.io/kubernetes-id: {{ .Values.app.name }}
    spec:
      {{- if and .Values.serviceAccount (default true .Values.serviceAccount.create) }}
      serviceAccountName: {{ .Values.app.name }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          {{- if .Values.image.digest }}
          # Using SHA digest for cross-namespace image pulls (OpenShift internal registry)
          image: "{{ .Values.image.host }}/{{ .Values.image.organization }}/{{ .Values.image.name }}@{{ .Values.image.digest }}"
          {{- else }}
          # Using tag for image reference (Quay/external registries)
          image: "{{ .Values.image.host }}/{{ .Values.image.organization }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.configMap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
          {{- end }}

