{{- if and .Values.serviceAccount (default true .Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/component: application
{{- end }}

